alter table BLOG_CATEGORY add constraint FK_BLOG_CATEGORY_ON_PARENT_CATEGORY foreign key (PARENT_CATEGORY_ID) references BLOG_CATEGORY(ID);
create index IDX_BLOG_CATEGORY_ON_PARENT_CATEGORY on BLOG_CATEGORY (PARENT_CATEGORY_ID);
